# Generated by Django 2.0 on 2017-12-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adduser', models.CharField(max_length=20, verbose_name='收件人')),
                ('addphone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('addsite', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('addpostcode', models.CharField(default='000000', max_length=6, verbose_name='邮编')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=40, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='onuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo'),
        ),
    ]
