# Generated by Django 2.0 on 2017-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='addNow',
            field=models.BooleanField(default=False, verbose_name='当前地址'),
        ),
    ]
