# Generated by Django 2.0 on 2018-01-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_addressinfo_addnow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressinfo',
            options={'verbose_name': '用户收货地址', 'verbose_name_plural': '用户收货地址'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='账户余额'),
            preserve_default=False,
        ),
    ]
