# Generated by Django 2.0 on 2017-12-14 14:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=20, verbose_name='商品名称')),
                ('gpic', models.ImageField(upload_to='df_goods', verbose_name='商品图片')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('isDelte', models.BooleanField(default=False, verbose_name='删除')),
                ('gunit', models.CharField(default='500g', max_length=20, verbose_name='单位')),
                ('gclick', models.IntegerField(verbose_name='人气')),
                ('gintro', models.CharField(max_length=200, verbose_name='简介')),
                ('grepertory', models.IntegerField(verbose_name='商品库存')),
                ('gcontent', tinymce.models.HTMLField(verbose_name='商品详情')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20, verbose_name='分类')),
                ('isDelete', models.BooleanField(default=False, verbose_name='删除')),
            ],
        ),
        migrations.AddField(
            model_name='goodinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=False, to='dailyfresh.TypeInfo'),
        ),
    ]
