# Generated by Django 2.0 on 2017-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_addressinfo_addnow'),
        ('dailyfresh', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('gcount', models.IntegerField(verbose_name='商品数量')),
                ('goods', models.ForeignKey(on_delete=False, to='dailyfresh.GoodInfo', verbose_name='商品信息')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('oaddress', models.CharField(max_length=150, verbose_name='收货地址')),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('oIsPay', models.BooleanField(default=False, verbose_name='付款')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总金额')),
                ('opay', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='实付金额')),
                ('user', models.ForeignKey(on_delete=False, to='df_user.UserInfo', verbose_name='用户名')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=True, to='dailyfresh.OrderInfo', verbose_name='订单编号'),
        ),
    ]
