# Generated by Django 2.0 on 2017-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyfresh', '0003_auto_20171226_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
